services:
    rf.cellulr.engine.co_container:
        class: Rf\CellulR\EngineBundle\CoreObject\Collection

    rf.cellulr.engine.finder:
        class: Rf\CellulR\EngineBundle\Finder\Finder
        public: false
        arguments:
            - "%cellulr.root_dir%"
            - "%cellulr.component_dir%"
            - "@=container.hasParameter('cellulr.core_object_dir') ? parameter('cellulr.core_object_dir') : ''"
            - "%kernel.root_dir%/cache/%kernel.environment%/CoreObjectAndCellCache.php"
            - "@rf.cellulr.engine.co_container"

    rf.cellulr.engine.twig_extension:
        class: Rf\CellulR\EngineBundle\Twig\CellulRExtension
        public: false
        arguments:
            - "@rf.cellulr.engine.co_container"
            - "@controller_resolver"
            - "@fragment.handler"
            - "@rf.cellulr.engine.finder"
        tags:
            - { name: twig.extension }

    rf.cellulr.engine.subscriber:
        class: Rf\CellulR\EngineBundle\EventSubscriber\CoreObjectSubscriber
        arguments:
          - "@twig"
          - "@rf.cellulr.engine.finder"
        tags:
            - { name: kernel.event_subscriber }

    rf.cellulr.engine.component_loader:
        class: Rf\CellulR\EngineBundle\Routing\ComponentLoader
        public: false
        arguments:
            - "@sensio_framework_extra.routing.loader.annot_dir"
            - "%cellulr.component_dir%"
            - "@=container.hasParameter('cellulr.core_object_dir') ? parameter('cellulr.core_object_dir') : ''"
        tags:
            - { name: routing.loader }
