sudo: false
dist: trusty
language: php

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1

before_script:
  - composer selfupdate --quiet
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - ./vendor/bin/phpunit